// auto-generated by scripts/timelapse/compile_timelapse.py — do not edit manually

export interface TimestampEntry {
  startSeconds: number;
  date: string;
}

export const TIMELAPSE_TIMESTAMPS: TimestampEntry[] = [
  { startSeconds: 0.0, date: "Mar 8, 2026" },
  { startSeconds: 3.0, date: "Apr 5, 2026" },
  { startSeconds: 6.0, date: "Apr 11, 2026" },
  { startSeconds: 9.0, date: "Apr 13, 2026" },
  { startSeconds: 9.333, date: "Apr 14, 2026" },
  { startSeconds: 10.333, date: "Apr 15, 2026" },
  { startSeconds: 11.333, date: "Apr 16, 2026" },
  { startSeconds: 12.333, date: "Apr 17, 2026" },
  { startSeconds: 13.333, date: "Apr 18, 2026" },
  { startSeconds: 14.333, date: "Apr 19, 2026" },
  { startSeconds: 15.333, date: "Apr 20, 2026" },
  { startSeconds: 16.333, date: "Apr 21, 2026" },
  { startSeconds: 17.333, date: "Apr 22, 2026" },
  { startSeconds: 18.333, date: "Apr 23, 2026" },
  { startSeconds: 19.333, date: "Apr 24, 2026" },
  { startSeconds: 20.333, date: "Apr 25, 2026" },
  { startSeconds: 21.333, date: "Apr 26, 2026" },
  { startSeconds: 22.333, date: "Apr 27, 2026" },
  { startSeconds: 23.333, date: "Apr 28, 2026" },
  { startSeconds: 24.333, date: "Apr 29, 2026" },
  { startSeconds: 30.133, date: "Apr 30, 2026" },
  { startSeconds: 34.933, date: "May 1, 2026" },
  { startSeconds: 39.733, date: "May 2, 2026" },
  { startSeconds: 44.533, date: "May 3, 2026" },
  { startSeconds: 49.333, date: "May 4, 2026" },
  { startSeconds: 54.133, date: "May 5, 2026" },
  { startSeconds: 58.933, date: "May 6, 2026" },
  { startSeconds: 63.733, date: "May 7, 2026" },
  { startSeconds: 68.533, date: "May 8, 2026" },
  { startSeconds: 73.333, date: "May 9, 2026" },
];
