// auto-generated by scripts/timelapse/compile_timelapse.py — do not edit manually

export interface TimestampEntry {
  startSeconds: number;
  date: string;
}

export const TIMELAPSE_TIMESTAMPS: TimestampEntry[] = [
  { startSeconds: 0.0, date: "Mar 8, 2026" },
  { startSeconds: 2.0, date: "Apr 5, 2026" },
  { startSeconds: 4.0, date: "Apr 11, 2026" },
  { startSeconds: 6.0, date: "Apr 13, 2026" },
  { startSeconds: 6.333, date: "Apr 14, 2026" },
  { startSeconds: 7.333, date: "Apr 15, 2026" },
  { startSeconds: 8.333, date: "Apr 16, 2026" },
  { startSeconds: 9.333, date: "Apr 17, 2026" },
  { startSeconds: 10.333, date: "Apr 18, 2026" },
  { startSeconds: 11.333, date: "Apr 19, 2026" },
  { startSeconds: 12.333, date: "Apr 20, 2026" },
  { startSeconds: 13.333, date: "Apr 21, 2026" },
  { startSeconds: 14.333, date: "Apr 22, 2026" },
  { startSeconds: 15.333, date: "Apr 23, 2026" },
  { startSeconds: 16.333, date: "Apr 24, 2026" },
  { startSeconds: 17.333, date: "Apr 25, 2026" },
  { startSeconds: 18.333, date: "Apr 26, 2026" },
  { startSeconds: 19.333, date: "Apr 27, 2026" },
  { startSeconds: 20.333, date: "Apr 28, 2026" },
  { startSeconds: 21.333, date: "Apr 29, 2026" },
  { startSeconds: 27.133, date: "Apr 30, 2026" },
  { startSeconds: 31.933, date: "May 1, 2026" },
  { startSeconds: 36.733, date: "May 2, 2026" },
  { startSeconds: 41.533, date: "May 3, 2026" },
  { startSeconds: 46.333, date: "May 4, 2026" },
  { startSeconds: 51.133, date: "May 5, 2026" },
  { startSeconds: 55.933, date: "May 6, 2026" },
  { startSeconds: 60.733, date: "May 7, 2026" },
  { startSeconds: 65.533, date: "May 8, 2026" },
  { startSeconds: 70.333, date: "May 9, 2026" },
  { startSeconds: 75.133, date: "May 10, 2026" },
  { startSeconds: 79.933, date: "May 11, 2026" },
  { startSeconds: 84.733, date: "May 12, 2026" },
  { startSeconds: 89.533, date: "May 13, 2026" },
  { startSeconds: 94.333, date: "May 14, 2026" },
];
