"""Centralized configuration for the Pac-Tyler data updater."""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SITE_ROOT_PARENT_LEVELS = 1
SITE_REPO_ROOT = REPO_ROOT.parents[SITE_ROOT_PARENT_LEVELS]

DOTENV_FILE_NAME = ".env"
DOTENV_SEARCH_PATHS = [
    REPO_ROOT / DOTENV_FILE_NAME,
    REPO_ROOT.parent / DOTENV_FILE_NAME,
]

OAUTH_PORT = 8080
REDIRECT_URI = f"http://localhost:{OAUTH_PORT}"

DEFAULT_LOOKBACK_DAYS = 365
RECENT_ACTIVITY_LOOKBACK_DAYS = 7
BATCH_SIZE = 5
ACTIVITY_DATE_INCREMENT_SECONDS = 1

LOOKBACK_DAYS_ENV_VAR = "PAC_TYLER_LOOKBACK_DAYS"
SILENCE_TOKEN_WARNINGS_ENV_VAR = "SILENCE_TOKEN_WARNINGS"

DATE_TIME_OUTPUT_TIMESPEC = "seconds"

MIN_COORDINATES_PER_FEATURE = 2
MIN_COORDINATE_DISTANCE_METERS = 0
MAX_COORDINATES_PER_FEATURE = 0

PAUSE_SPLIT_THRESHOLD_KM = 2.0

STRAVA_SCOPES = ["read_all", "activity:read_all"]
STRAVA_STREAM_TYPES = ["latlng"]
STRAVA_STREAM_RESOLUTION = "medium"

RATE_LIMIT_SLEEP_SECONDS = 15 * 60

MIN_LATITUDE = -90.0
MAX_LATITUDE = 90.0
MIN_LONGITUDE = -180.0
MAX_LONGITUDE = 180.0

JSON_INDENT = 4
METERS_PER_MILE = 1609.34

GEOJSON_FILE = REPO_ROOT / "cleaned_output.geojson"
PUBLIC_DATA_DIR = SITE_REPO_ROOT / "public" / "data"
DERIVED_DATA_DIR = PUBLIC_DATA_DIR
DERIVED_ACTIVITY_JSON = DERIVED_DATA_DIR / "pac-tyler-activities.json"